const Coin = [
  {
    id: "btc-bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    rank: 1,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "eth-ethereum",
    name: "Ethereum",
    symbol: "ETH",
    rank: 2,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "usdt-tether",
    name: "Tether",
    symbol: "USDT",
    rank: 3,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "bnb-binance-coin",
    name: "Binance Coin",
    symbol: "BNB",
    rank: 4,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "usdc-usd-coin",
    name: "USD Coin",
    symbol: "USDC",
    rank: 5,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "hex-hex",
    name: "HEX",
    symbol: "HEX",
    rank: 6,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "sol-solana",
    name: "Solana",
    symbol: "SOL",
    rank: 7,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "xrp-xrp",
    name: "XRP",
    symbol: "XRP",
    rank: 8,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "ada-cardano",
    name: "Cardano",
    symbol: "ADA",
    rank: 9,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "luna-terra",
    name: "Terra",
    symbol: "LUNA",
    rank: 10,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "avax-avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    rank: 11,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "doge-dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    rank: 12,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "busd-binance-usd",
    name: "Binance USD",
    symbol: "BUSD",
    rank: 13,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "dot-polkadot",
    name: "Polkadot",
    symbol: "DOT",
    rank: 14,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "ust-terrausd",
    name: "TerraUSD",
    symbol: "UST",
    rank: 15,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "near-near-protocol",
    name: "Near Protocol",
    symbol: "NEAR",
    rank: 16,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "shib-shiba-inu",
    name: "Shiba Inu",
    symbol: "SHIB",
    rank: 17,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "wbtc-wrapped-bitcoin",
    name: "Wrapped Bitcoin",
    symbol: "WBTC",
    rank: 18,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "matic-polygon",
    name: "Polygon",
    symbol: "MATIC",
    rank: 19,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "steth-lido-staked-ether",
    name: "Lido Staked Ether",
    symbol: "STETH",
    rank: 20,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "atom-cosmos",
    name: "Cosmos",
    symbol: "ATOM",
    rank: 21,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "ltc-litecoin",
    name: "Litecoin",
    symbol: "LTC",
    rank: 22,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "cro-cryptocom-chain",
    name: "Crypto.com Coin",
    symbol: "CRO",
    rank: 23,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "trx-tron",
    name: "TRON",
    symbol: "TRX",
    rank: 24,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "dai-dai",
    name: "Dai",
    symbol: "DAI",
    rank: 25,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "bch-bitcoin-cash",
    name: "Bitcoin Cash",
    symbol: "BCH",
    rank: 26,
    is_new: false,
    is_active: true,
    type: "coin",
  },
  {
    id: "ftt-ftx-token",
    name: "FTX Token",
    symbol: "FTT",
    rank: 27,
    is_new: false,
    is_active: true,
    type: "token",
  },
  {
    id: "link-chainlink",
    name: "Chainlink",
    symbol: "LINK",
    rank: 28,
    is_new: false,
    is_active: true,
    type: "token",
  },
];

export default Coin;
